# -*- coding: utf-8 -*-

"""
brahma

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from tests.test_helper import TestHelper
from brahma.api_helper import APIHelper
from brahma.models.https_brahma_digivalet_com_api_datasourcesrequest import HttpsBrahmaDigivaletComApiDatasourcesrequest


class MiscControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(MiscControllerTests, cls).setUpClass()
        cls.controller = cls.client.misc
        cls.response_catcher = cls.controller.http_call_back

    # Todo: Add description for test test_https_brahma_digivalet_com_api_datasources
    def test_https_brahma_digivalet_com_api_datasources(self):
        # Parameters for the API call
        accept = 'application/json'
        body = APIHelper.json_deserialize('{"name":"CMB","type":"influxdb","url":"https://dmon.digivalet.com"'
            ',"Org":"shrey","access":"proxy","basicAuth":false,"database":"cmbd'
            'b","user":"cmbuser","secureJsonData":{"password":"123456"}}', HttpsBrahmaDigivaletComApiDatasourcesrequest.from_dictionary)

        # Perform the API call through the SDK function
        self.controller.https_brahma_digivalet_com_api_datasources(accept, body)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

