# -*- coding: utf-8 -*-

"""
brahma

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from brahma.decorators import lazy_property
from brahma.configuration import Configuration
from brahma.configuration import Environment
from brahma.http.auth.o_auth_2 import OAuth2
from brahma.controllers.misc_controller import MiscController


class BrahmaClient(object):

    @lazy_property
    def misc(self):
        return MiscController(self.config, self.auth_managers)

    def __init__(self, http_client_instance=None,
                 override_http_client_configuration=False, http_call_back=None,
                 timeout=60, max_retries=0, backoff_factor=2,
                 retry_statuses=[408, 413, 429, 500, 502, 503, 504, 521, 522, 524],
                 retry_methods=['GET', 'PUT'],
                 environment=Environment.PRODUCTION, access_token='',
                 config=None):
        if config is None:
            self.config = Configuration(
                                         http_client_instance=http_client_instance,
                                         override_http_client_configuration=override_http_client_configuration,
                                         http_call_back=http_call_back,
                                         timeout=timeout,
                                         max_retries=max_retries,
                                         backoff_factor=backoff_factor,
                                         retry_statuses=retry_statuses,
                                         retry_methods=retry_methods,
                                         environment=environment,
                                         access_token=access_token)
        else:
            self.config = config
        self.initialize_auth_managers(self.config)

    def initialize_auth_managers(self, config):
        self.auth_managers = { key: None for key in ['global']}
        self.auth_managers['global'] = OAuth2(config.access_token)
        return self.auth_managers
