# -*- coding: utf-8 -*-

"""
brahma

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from brahma.api_helper import APIHelper
from brahma.configuration import Server
from brahma.controllers.base_controller import BaseController


class MiscController(BaseController):

    """A Controller to access Endpoints in the brahma API."""
    def __init__(self, config, auth_managers):
        super(MiscController, self).__init__(config, auth_managers)

    def https_brahma_digivalet_com_api_datasources(self,
                                                   accept,
                                                   body):
        """Does a POST request to /datasources.

        TODO: type endpoint description here.

        Args:
            accept (string): TODO: type description here.
            body (HttpsBrahmaDigivaletComApiDatasourcesrequest): TODO: type
                description here.

        Returns:
            void: Response from the API.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        # Prepare query URL
        _url_path = '/datasources'
        _query_builder = self.config.get_base_uri()
        _query_builder += _url_path
        _query_url = APIHelper.clean_url(_query_builder)

        # Prepare headers
        _headers = {
            'Accept': accept,
            'Content-Type': 'application/json'
        }

        # Prepare and execute request
        _request = self.config.http_client.post(_query_url, headers=_headers, parameters=APIHelper.json_serialize(body))
        # Apply authentication scheme on request
        self.apply_auth_schemes(_request, 'global')

        _response = self.execute_request(_request)
        self.validate_response(_response)
